# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('tagline', models.TextField()),
            ],
            options={
                'verbose_name': '公司名称',
                'verbose_name_plural': '公司名称',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 5, 16, 16, 16, 2, 885945, tzinfo=utc))),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='intro.Author')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.Company')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
