# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20160512_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 5, 13, 14, 44, 18, 255365, tzinfo=utc))),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.TextField(default=datetime.datetime(2016, 5, 13, 14, 44, 33, 940023, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='content',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
