# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160513_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='authors',
            field=models.ManyToManyField(to='company.Author'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 14, 46, 32, 855955, tzinfo=utc)),
        ),
    ]
