# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20160513_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '公司名称', 'verbose_name_plural': '公司名称'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 16, 16, 2, 888022, tzinfo=utc)),
        ),
    ]
